backtraces_path = "/tmp/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
#neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "gruvbox"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [ "Anonymice Nerd Font" ] # Will use the bundled Fira Code Nerd Font by default
size = 12.0
