general.import = ["/var/home/jpm/.dotfiles/.config/alacritty/alacritty.toml", "/var/home/jpm/.dotfiles/.config/alacritty/fedora.toml"]

[env]
TERM_TITLE = "Alacritty (Fedora Ephemeral)"

[terminal.shell]
args = ["ephemeral", "-i", "fedora:39"]
program = "/usr/bin/distrobox"

[window]
title = "Alacritty - Fedora (Ephemeral)"

[window.class]
general = "Alacritty-fedora-ephemeral"
instance = "Alacritty-fedora-ephemeral"

[terminal]
