general.import = ["/var/home/jpm/.dotfiles/.config/alacritty/fedora.toml"]

[colors.bright]
black = "#000000"
blue = "#202020"
yellow = "#202020"
cyan = "#404040"
red = "#404040"
green = "#606060"
magenta = "#606060"
white = "#ffffff"

[colors.normal]
black = "#000000"
blue = "#202020"
yellow = "#202020"
cyan = "#404040"
red = "#404040"
green = "#606060"
magenta = "#606060"
white = "#ffffff"

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[env]
TERM_TITLE = "Alacritty (Fedora eInk)"
TERM_LIGHT = "1"

[font]
size = 11.0

[font.bold]
family = "Anonymice Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Anonymice Nerd Font"
style = "SemiBold"

[font.italic]
family = "Anonymice Nerd Font"
style = "Light"

[font.normal]
family = "Anonymice Nerd Font"
style = "Regular"

[terminal.shell]
args = ["enter", "fedora"]
program = "/usr/bin/distrobox"

[window]
title = "Alacritty - Fedora (Distrobox) eInk"

[window.class]
general = "Alacritty-fedora-eink"
instance = "Alacritty-fedora-eink"

[terminal]
