general.import = ["/var/home/jpm/.dotfiles/.config/alacritty/alacritty.toml"]

[colors.bright]
black = "#5E5C64"
blue = "#83A598"
cyan = "#8EC07C"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#EBDBB2"
yellow = "#FABD2F"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689D6A"
green = "#98971A"
magenta = "#B16386"
red = "#CC240A"
white = "#A89984"
yellow = "#D79921"

[colors.primary]
background = "#282828"
foreground = "#EBDBB2"

[env]
TERM_TITLE = "Alacritty (Grave)"

[font]
size = 11.0

[font.bold]
family = "Anonymice Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Anonymice Nerd Font"
style = "SemiBold"

[font.italic]
family = "Anonymice Nerd Font"
style = "Light"

[font.normal]
family = "Anonymice Nerd Font"
style = "Regular"

[terminal.shell]
args = ["enter", "fedora"]
program = "/usr/bin/distrobox"

[window]
title = "Alacritty - Fedora (Grave)"

[window.class]
general = "Alacritty-grave"
instance = "Alacritty-grave"

[terminal]
